[package]
name = "wwa"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = ["analyze", "breakpoint"]
analyze = []
breakpoint = ["dep:rustc-hash"]
serde = ["dep:serde"]

[dependencies]
rustc-hash = { version = "2.1.2", optional = true }
serde = { version = "1.0.228", optional = true, features = ["derive"] }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "breakpoint"
harness = false
required-features = ["breakpoint"]
